# Generated by Django 4.0.4 on 2022-04-19 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('is_given', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GuestEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_first_name', models.CharField(max_length=100)),
                ('guest_last_name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100, null=True)),
                ('enter_datetime', models.DateTimeField(auto_now_add=True)),
                ('exit_datetime', models.DateTimeField(blank=True, null=True)),
                ('keeper_full_name', models.CharField(max_length=100)),
                ('notes', models.CharField(blank=True, max_length=1000, null=True)),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.card')),
            ],
        ),
    ]
