# Generated by Django 4.0.4 on 2022-04-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestentry',
            name='guest_last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='guestentry',
            name='keeper_full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
