# Generated by Django 4.0.4 on 2022-04-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestentry',
            name='exit_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
