# Generated by Django 4.0.4 on 2022-04-29 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ('id', 'is_given')},
        ),
        migrations.AlterModelOptions(
            name='guestentry',
            options={'ordering': ('enter_datetime',)},
        ),
    ]
