# Generated by Django 4.0.4 on 2022-04-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_guestentry_guest_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestentry',
            name='enter_datetime',
            field=models.DateTimeField(),
        ),
    ]
