# Generated by Django 4.0.4 on 2022-04-15 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_keeper_guestentry_keeper_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestentry',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='guestentry',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.card'),
        ),
    ]
