# Generated by Django 4.0.4 on 2022-04-15 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_guestentry_company_alter_guestentry_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestentry',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.card'),
        ),
        migrations.AlterField(
            model_name='guestentry',
            name='notes',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
